version: '3.8'

services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - api_gateway
    networks:
      - backend
      - monitoring

  api_gateway:
    image: kong:latest
    container_name: api_gateway
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_DECLARATIVE_CONFIG: "/kong.yml"
    volumes:
      - ./kong.yml:/kong.yml:ro
    depends_on:
      - keycloak
      - service_one
    networks:
      - backend
      - monitoring

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - backend

  reverse_proxy_metrics:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: reverse_proxy_metrics
    ports:
      - "9113:9113"
    command: -nginx.scrape-uri=http://reverse_proxy/nginx_status
    depends_on:
      - reverse_proxy
    networks:
      - monitoring

  service_one:
    image: python:3.9-slim
    container_name: service_one
    command: >
      sh -c "
      pip install flask &&
      echo \"from flask import Flask, jsonify;
      app = Flask(__name__);
      @app.route('/service-one', methods=['GET'])
      def service_one():
          return jsonify({'message': 'Hello from Service One'});
      app.run(host='0.0.0.0', port=5000)\" > app.py &&
      python app.py"
    ports:
      - "5001:5000"
    networks:
      - backend
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - monitoring

  opensearch_dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch_dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
    depends_on:
      - opensearch
    networks:
      - monitoring

networks:
  backend:
    driver: bridge
  monitoring:
    driver: bridge

