global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api_gateway:8001']
  - job_name: 'service_one'
    static_configs:
      - targets: ['service_one:5000']
  - job_name: 'reverse_proxy'
    static_configs:
      - targets: ['reverse_proxy:443']
  - job_name: 'nginx'
    static_configs:
      - targets: ['reverse_proxy_metrics:9113']
